eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
    instance:
        client:
            serviceUrl:
                defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
        prefer-ip-address: true   
